name: visualize
on: push
jobs:
  visualize-job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.2
        - name: Repo Visualizer
          uses: githubocto/repo-visualizer@0.9.1
          with:
            artifact_name: "diagram"
